# Generated by Django 3.1.3 on 2020-11-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzerias',
            old_name='nae',
            new_name='name',
        ),
    ]
